#!/bin/bash

rm -rf .state
mkdir .state

touch .state/target-commit .state/step-count .state/error-count .state/options
echo "1" > .state/step-count
echo "0" > .state/error-count

HIKING_BOOT_OPTIONS=(\
'Ultra-Lightweight' \
'Waterproof' \
'Insulated' \
'Barefoot-Style' \
'High-Traction' \
'Eco-Friendly' \
'Wide-Toe' \
'Ankle-Support' \
)
HIKING_BOOT_COUNT=${#HIKING_BOOT_OPTIONS[@]}
for (( i = HIKING_BOOT_COUNT - 1; i > 0; i-- )); do
    j=$(( RANDOM % (i + 1) ))

    temp="${HIKING_BOOT_OPTIONS[$i]}"
    HIKING_BOOT_OPTIONS[$i]="${HIKING_BOOT_OPTIONS[$j]}"
    HIKING_BOOT_OPTIONS[$j]="$temp"
done

HIKING_BOOT_OPTIONS=( "${HIKING_BOOT_OPTIONS[@]:0:5}" )

for OPTION in "${HIKING_BOOT_OPTIONS[@]}"
do
  echo $OPTION >> .state/options
done

TARGET_OPTION="${HIKING_BOOT_OPTIONS[1]}"
echo "${TARGET_OPTION}"
echo "${TARGET_OPTION}" > .state/target-commit

git checkout -q main

echo "*************"
echo "HIKE RESEARCH"
echo "*************"
echo -e "\n"

./next
