#!/bin/bash

OLD_STEP_COUNT=`cat .state/step-count`

if [ $OLD_STEP_COUNT -gt 5 ]
  check_victory
elif [ $OLD_STEP_COUNT -eq 5 ]
  NEW_STEP_COUNT=$OLD_STEP_COUNT + 1
  echo $NEW_STEP_COUNT > .state/step-count

  git checkout main
else
  CURRENT_OPTION=sed -n -e "${OLD_STEP_COUNT}p"
  git switch $CURRENT_OPTION
  cat current-boot-description.md
  NEW_STEP_COUNT=$OLD_STEP_COUNT + 1
  echo $NEW_STEP_COUNT > .state/step-count
fi

check_victory () {
  CURRENT_COMMIT=`git log -1 --pretty=%B`
  echo $CURRENT_COMMIT
  TARGET_COMMIT=`cat .state/target-commit`
  OLD_ERROR_COUNT=`cat .state/error-count`

  if [ $CURRENT_COMMIT -eq $TARGET_COMMIT ]
    echo 'You won!'
    if [ $OLD_ERROR_COUNT -gt 0 ]
      echo "Finished with $OLD_ERROR_COUNT mistakes"
    fi
  else
    NEW_ERROR_COUNT=$OLD_ERROR_COUNT + 1
    echo $NEW_ERROR_COUNT > .state/error-count

    echo 'Not quite'
  fi
}
