#!/bin/bash

git config advice.detachedHead false

STEP_COUNT=`cat .state/step-count`
echo "$STEP_COUNT"

if [[ "$STEP_COUNT" -gt 5 ]]; then
  check_victory
elif [[ "$STEP_COUNT" -eq 5 ]]; then
  ((STEP_COUNT+=1))
  echo $STEP_COUNT > .state/step-count

  TARGET_COMMIT=`cat .state/target-commit`
  echo "You've reviewed the options and decided to go with the ${TARGET_COMMIT} hiking boots. Use the reflog to check out that commit and run this command again."

  git checkout main
else
  CURRENT_OPTION=$(sed -n -e "${STEP_COUNT}p" '.state/options')
  git checkout ":/${CURRENT_OPTION}"
  echo -e "\n\n\n"
  cat current-boot-description.md
  ((STEP_COUNT+=1))
  echo "$STEP_COUNT" > .state/step-count
fi

check_victory () {
  CURRENT_COMMIT=`git log -1 --pretty=%B`
  TARGET_COMMIT=`cat .state/target-commit`
  OLD_ERROR_COUNT=`cat .state/error-count`

  if [[ "$CURRENT_COMMIT" == "$TARGET_COMMIT" ]]; then
    echo 'You won!'
    if [[ $OLD_ERROR_COUNT -gt 0 ]]; then
      echo "Finished with $OLD_ERROR_COUNT mistakes"
    fi
  else
    NEW_ERROR_COUNT=$OLD_ERROR_COUNT + 1
    echo "$NEW_ERROR_COUNT" > .state/error-count

    echo 'Not quite'
  fi
}
